name: MLOps_proj1
channels:
  - conda-forge
  - nvidia
  - rapidsai
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pytorch
  - torchvision
  - lightning
  - optuna
